### ISSUE TITLE
Support for FSF GNAT 11.1

### ISSUE THREAD

**Issue by treiher** [Componolit/RecordFlux-language#42]
Related to Componolit/RecordFlux#674

**Comment by treiher** [comment]
Compiling the parser with FSF GNAT 11.2 leads to the following error:

```Console
$ ./setup.py generate_parser
[...]
Generating source for librflxlang...
Generation complete!
Building the generated source code
gpr.gpr:26:04: value "static-pic" is illegal for typed string "bld"
gprbuild: "/tmp/RecordFlux-language/build/langkit/librflxlang.gpr" processing failed
Build failed: error while running gprbuild -p -j16 -P/tmp/RecordFlux-language/build/langkit/librflxlang.gpr -XBUILD_MODE=dev -XLIBRARY_TYPE=static-pic -XGPR_BUILD=static-pic -XXMLADA_BUILD=static-pic -XLIBRARY_TYPE=static-pic -aP /tmp/RecordFlux-language/contrib/gnatcoll-bindings/iconv -aP /tmp/RecordFlux-language/contrib/gnatcoll-bindings/gmp -aP /tmp/RecordFlux-language/contrib/langkit/support -aP /tmp/RecordFlux-language/contrib/langkit/langkit:
    Command '['gprbuild', '-p', '-j16', '-P/tmp/RecordFlux-language/build/langkit/librflxlang.gpr', '-XBUILD_MODE=dev', '-XLIBRARY_TYPE=static-pic', '-XGPR_BUILD=static-pic', '-XXMLADA_BUILD=static-pic', '-XLIBRARY_TYPE=static-pic', '-aP', '/tmp/RecordFlux-language/contrib/gnatcoll-bindings/iconv', '-aP', '/tmp/RecordFlux-language/contrib/gnatcoll-bindings/gmp', '-aP', '/tmp/RecordFlux-language/contrib/langkit/support', '-aP', '/tmp/RecordFlux-language/contrib/langkit/langkit']' returned non-zero exit status 4.
```

The error seems to be caused by the different interpretation of `GPR_BUILD` in `gpr.gpr`.

#### FSF GNAT 11.2

```ada
   21 library project GPR is
   22 
   23    for languages use ("Ada", "C");
   24 
   25    type Build_Type is ("debug", "production", "coverage", "profiling");
   26    Bld : Build_Type := external ("GPR_BUILD",
   27                                  external ("BUILD", "production"));
```

#### GNAT Community 2021

```ada
    9 library project GPR is
   10    type BUILD_KIND is ("static", "relocatable", "static-pic");
   11    BUILD : BUILD_KIND := external("GPR_BUILD", external("LIBRARY_TYPE", "static"));
```

Langkit is setting `GPR_BUILD` in `langkit/libmanage.py` since https://github.com/AdaCore/langkit/pull/115.

**Comment by treiher** [comment]
After removing the problematic `GPR_BUILD` option, an error occurs after the successful compilation:

```Console
    Build Libraries
       [gprlib]       gnatcoll_gmp.lexch
       [gprlib]       gnatcoll_iconv.lexch
       [archive]      libgnatcoll_gmp.a
       [archive]      libgnatcoll_iconv.a
       [index]        libgnatcoll_iconv.a
       [index]        libgnatcoll_gmp.a
       [gprlib]       langkit_support.lexch
       [bind SAL]     langkit_support
       [Ada]          b__langkit_support.adb
       [gprlib]       rflxlang.lexch
       [objcopy]      p__langkit_support_0.o
       [archive]      liblangkit_support.a
       [index]        liblangkit_support.a
       [bind SAL]     rflxlang
       [Ada]          b__rflxlang.adb
       [objcopy]      p__rflxlang_0.o
       [archive]      librflxlang.a
       [index]        librflxlang.a
    Compilation complete!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3r435aus/setup.py", line 183, in <module>                                             
        "librflxlang.so",
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup                                                
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands                                         
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command                                          
        cmd_obj.run()
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 299, in run
        self.find_sources()
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
        mm.run()
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 541, in run
        self.add_defaults()
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3.7/distutils/command/sdist.py", line 226, in add_defaults                                
        self._add_defaults_python()
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/command/sdist.py", line 107, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.7/distutils/cmd.py", line 298, in get_finalized_command                                 
        cmd_obj = self.distribution.get_command_obj(command, create)                                                 
      File "/usr/lib/python3.7/distutils/dist.py", line 858, in get_command_obj                                      
        cmd_obj = self.command_obj[command] = klass(self)
      File "/tmp/RecordFlux-language/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 172, in __init__
        _Command.__init__(self, dist)
      File "/usr/lib/python3.7/distutils/cmd.py", line 62, in __init__                                               
        self.initialize_options()
      File "/tmp/pip-req-build-3r435aus/setup.py", line 128, in initialize_options                                   
        "-lgmp",
      File "/tmp/pip-req-build-3r435aus/setup.py", line 107, in <genexpr>                                            
        for a in [
      File "/tmp/pip-req-build-3r435aus/setup.py", line 56, in get_gcc_location                                      
        raise InstallError(f'File "{name}" not found')
    __main__.InstallError: File "gpr/static-pic/gpr/libgpr.a" not found
```

**Comment by treiher** [comment]
The issues seem not to be caused by langkit, but by the way langkit is used in `setup.py`. The packaging process is currently reworked in #37. That possibly fixes the issues. This issue will be deferred until the change of the packaging has been completed.
